//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for HealthChecksDatabase.
const (
	HealthChecksDatabaseError HealthChecksDatabase = "error"
	HealthChecksDatabaseOk    HealthChecksDatabase = "ok"
)

// Valid indicates whether the value is a known member of the HealthChecksDatabase enum.
func (e HealthChecksDatabase) Valid() bool {
	switch e {
	case HealthChecksDatabaseError:
		return true
	case HealthChecksDatabaseOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthChecksMqtt.
const (
	Connected    HealthChecksMqtt = "connected"
	Disabled     HealthChecksMqtt = "disabled"
	Disconnected HealthChecksMqtt = "disconnected"
)

// Valid indicates whether the value is a known member of the HealthChecksMqtt enum.
func (e HealthChecksMqtt) Valid() bool {
	switch e {
	case Connected:
		return true
	case Disabled:
		return true
	case Disconnected:
		return true
	default:
		return false
	}
}

// Defines values for HealthLiveResponseStatus.
const (
	HealthLiveResponseStatusOk HealthLiveResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthLiveResponseStatus enum.
func (e HealthLiveResponseStatus) Valid() bool {
	switch e {
	case HealthLiveResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthReadyResponseStatus.
const (
	HealthReadyResponseStatusDegraded HealthReadyResponseStatus = "degraded"
	HealthReadyResponseStatusReady    HealthReadyResponseStatus = "ready"
	HealthReadyResponseStatusStarting HealthReadyResponseStatus = "starting"
)

// Valid indicates whether the value is a known member of the HealthReadyResponseStatus enum.
func (e HealthReadyResponseStatus) Valid() bool {
	switch e {
	case HealthReadyResponseStatusDegraded:
		return true
	case HealthReadyResponseStatusReady:
		return true
	case HealthReadyResponseStatusStarting:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded HealthResponseStatus = "degraded"
	HealthResponseStatusOk       HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusDegraded:
		return true
	case HealthResponseStatusOk:
		return true
	default:
		return false
	}
}

// CameraHealthCheck defines model for CameraHealthCheck.
type CameraHealthCheck struct {
	Online int `json:"online"`
	Total  int `json:"total"`
}

// HealthChecks defines model for HealthChecks.
type HealthChecks struct {
	Cameras  CameraHealthCheck    `json:"cameras"`
	Database HealthChecksDatabase `json:"database"`
	Mqtt     HealthChecksMqtt     `json:"mqtt"`
	Storage  StorageHealthCheck   `json:"storage"`
}

// HealthChecksDatabase defines model for HealthChecks.Database.
type HealthChecksDatabase string

// HealthChecksMqtt defines model for HealthChecks.Mqtt.
type HealthChecksMqtt string

// HealthLiveResponse defines model for HealthLiveResponse.
type HealthLiveResponse struct {
	Status HealthLiveResponseStatus `json:"status"`
	Uptime string                   `json:"uptime"`
}

// HealthLiveResponseStatus defines model for HealthLiveResponse.Status.
type HealthLiveResponseStatus string

// HealthReadyResponse defines model for HealthReadyResponse.
type HealthReadyResponse struct {
	Checks ReadyChecks               `json:"checks"`
	Status HealthReadyResponseStatus `json:"status"`
}

// HealthReadyResponseStatus defines model for HealthReadyResponse.Status.
type HealthReadyResponseStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Checks  HealthChecks         `json:"checks"`
	Status  HealthResponseStatus `json:"status"`
	Uptime  string               `json:"uptime"`
	Version string               `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ReadyCameraCheck defines model for ReadyCameraCheck.
type ReadyCameraCheck struct {
	Degraded int `json:"degraded"`
	Total    int `json:"total"`
}

// ReadyChecks defines model for ReadyChecks.
type ReadyChecks struct {
	Cameras     ReadyCameraCheck   `json:"cameras"`
	Database    string             `json:"database"`
	Initialized bool               `json:"initialized"`
	Storage     *ReadyStorageCheck `json:"storage,omitempty"`
}

// ReadyStorageCheck defines model for ReadyStorageCheck.
type ReadyStorageCheck struct {
	DiskLow         *bool `json:"disk_low,omitempty"`
	RecordingPaused *bool `json:"recording_paused,omitempty"`
}

// RecompressionStats defines model for RecompressionStats.
type RecompressionStats struct {
	BytesReclaimed       int64      `json:"bytes_reclaimed"`
	Enabled              bool       `json:"enabled"`
	LastRun              *time.Time `json:"last_run,omitempty"`
	SegmentsRecompressed int        `json:"segments_recompressed"`
}

// StorageHealthCheck defines model for StorageHealthCheck.
type StorageHealthCheck struct {
	DiskAvailable   string             `json:"disk_available"`
	DiskLow         bool               `json:"disk_low"`
	Recompression   RecompressionStats `json:"recompression"`
	RecordingPaused bool               `json:"recording_paused"`
	Used            string             `json:"used"`
	UsedBytes       int64              `json:"used_bytes"`
}

// SystemResponse defines model for SystemResponse.
type SystemResponse struct {
	Cameras      int    `json:"cameras"`
	Decoder      string `json:"decoder"`
	Online       int    `json:"online"`
	Storage      string `json:"storage"`
	StorageBytes int64  `json:"storage_bytes"`
	Uptime       string `json:"uptime"`
	Version      string `json:"version"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Full health check
	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /api/health/live)
	GetHealthLive(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /api/health/ready)
	GetHealthReady(w http.ResponseWriter, r *http.Request)
	// OpenAPI specification
	// (GET /api/openapi.json)
	GetOpenAPISpec(w http.ResponseWriter, r *http.Request)
	// System information
	// (GET /api/system)
	GetSystem(w http.ResponseWriter, r *http.Request)
	// Trigger manual recompression
	// (POST /api/system/recompress/trigger)
	TriggerRecompression(w http.ResponseWriter, r *http.Request)
	// Prometheus metrics
	// (GET /metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthLive operation middleware
func (siw *ServerInterfaceWrapper) GetHealthLive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthLive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthReady operation middleware
func (siw *ServerInterfaceWrapper) GetHealthReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenAPISpec operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPISpec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenAPISpec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystem operation middleware
func (siw *ServerInterfaceWrapper) GetSystem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerRecompression operation middleware
func (siw *ServerInterfaceWrapper) TriggerRecompression(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerRecompression(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/api/health/live", wrapper.GetHealthLive)
	m.HandleFunc("GET "+options.BaseURL+"/api/health/ready", wrapper.GetHealthReady)
	m.HandleFunc("GET "+options.BaseURL+"/api/openapi.json", wrapper.GetOpenAPISpec)
	m.HandleFunc("GET "+options.BaseURL+"/api/system", wrapper.GetSystem)
	m.HandleFunc("POST "+options.BaseURL+"/api/system/recompress/trigger", wrapper.TriggerRecompression)
	m.HandleFunc("GET "+options.BaseURL+"/metrics", wrapper.GetMetrics)

	return m
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthLiveRequestObject struct {
}

type GetHealthLiveResponseObject interface {
	VisitGetHealthLiveResponse(w http.ResponseWriter) error
}

type GetHealthLive200JSONResponse HealthLiveResponse

func (response GetHealthLive200JSONResponse) VisitGetHealthLiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthReadyRequestObject struct {
}

type GetHealthReadyResponseObject interface {
	VisitGetHealthReadyResponse(w http.ResponseWriter) error
}

type GetHealthReady200JSONResponse HealthReadyResponse

func (response GetHealthReady200JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthReady503JSONResponse HealthReadyResponse

func (response GetHealthReady503JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetOpenAPISpecRequestObject struct {
}

type GetOpenAPISpecResponseObject interface {
	VisitGetOpenAPISpecResponse(w http.ResponseWriter) error
}

type GetOpenAPISpec200JSONResponse map[string]interface{}

func (response GetOpenAPISpec200JSONResponse) VisitGetOpenAPISpecResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSystemRequestObject struct {
}

type GetSystemResponseObject interface {
	VisitGetSystemResponse(w http.ResponseWriter) error
}

type GetSystem200JSONResponse SystemResponse

func (response GetSystem200JSONResponse) VisitGetSystemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TriggerRecompressionRequestObject struct {
}

type TriggerRecompressionResponseObject interface {
	VisitTriggerRecompressionResponse(w http.ResponseWriter) error
}

type TriggerRecompression202Response struct {
}

func (response TriggerRecompression202Response) VisitTriggerRecompressionResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type TriggerRecompression409TextResponse string

func (response TriggerRecompression409TextResponse) VisitTriggerRecompressionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(409)

	_, err := w.Write([]byte(response))
	return err
}

type GetMetricsRequestObject struct {
}

type GetMetricsResponseObject interface {
	VisitGetMetricsResponse(w http.ResponseWriter) error
}

type GetMetrics200TextResponse string

func (response GetMetrics200TextResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Full health check
	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Liveness probe
	// (GET /api/health/live)
	GetHealthLive(ctx context.Context, request GetHealthLiveRequestObject) (GetHealthLiveResponseObject, error)
	// Readiness probe
	// (GET /api/health/ready)
	GetHealthReady(ctx context.Context, request GetHealthReadyRequestObject) (GetHealthReadyResponseObject, error)
	// OpenAPI specification
	// (GET /api/openapi.json)
	GetOpenAPISpec(ctx context.Context, request GetOpenAPISpecRequestObject) (GetOpenAPISpecResponseObject, error)
	// System information
	// (GET /api/system)
	GetSystem(ctx context.Context, request GetSystemRequestObject) (GetSystemResponseObject, error)
	// Trigger manual recompression
	// (POST /api/system/recompress/trigger)
	TriggerRecompression(ctx context.Context, request TriggerRecompressionRequestObject) (TriggerRecompressionResponseObject, error)
	// Prometheus metrics
	// (GET /metrics)
	GetMetrics(ctx context.Context, request GetMetricsRequestObject) (GetMetricsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthLive operation middleware
func (sh *strictHandler) GetHealthLive(w http.ResponseWriter, r *http.Request) {
	var request GetHealthLiveRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthLive(ctx, request.(GetHealthLiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthLive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthLiveResponseObject); ok {
		if err := validResponse.VisitGetHealthLiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthReady operation middleware
func (sh *strictHandler) GetHealthReady(w http.ResponseWriter, r *http.Request) {
	var request GetHealthReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthReady(ctx, request.(GetHealthReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthReadyResponseObject); ok {
		if err := validResponse.VisitGetHealthReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOpenAPISpec operation middleware
func (sh *strictHandler) GetOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	var request GetOpenAPISpecRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPISpec(ctx, request.(GetOpenAPISpecRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPISpec")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOpenAPISpecResponseObject); ok {
		if err := validResponse.VisitGetOpenAPISpecResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSystem operation middleware
func (sh *strictHandler) GetSystem(w http.ResponseWriter, r *http.Request) {
	var request GetSystemRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystem(ctx, request.(GetSystemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSystemResponseObject); ok {
		if err := validResponse.VisitGetSystemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerRecompression operation middleware
func (sh *strictHandler) TriggerRecompression(w http.ResponseWriter, r *http.Request) {
	var request TriggerRecompressionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerRecompression(ctx, request.(TriggerRecompressionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerRecompression")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerRecompressionResponseObject); ok {
		if err := validResponse.VisitTriggerRecompressionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetrics operation middleware
func (sh *strictHandler) GetMetrics(w http.ResponseWriter, r *http.Request) {
	var request GetMetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetrics(ctx, request.(GetMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricsResponseObject); ok {
		if err := validResponse.VisitGetMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RX22/bthf+Vwj+fo9c7LXdgOktKLAtu7RBXPQlMAJaOpHZSCRLHrnzCv3vAy+WdaHl",
	"ZGmwN1vi5fu+852LvtJc1VpJkGhp9pXafAs19z/f8hoM/xV4hdu3W8gf3ENtlAaDAvwSJSshwf3CvQaa",
	"USERSjC0ZRQV8ir1qmXUwOdGGChodhvXscNZa3bYoDafIEd3VA+DnYLIPU7/8/8G7mlG/7c4klpERosp",
	"nZbRgiPfcOspgGxqB0g9UEbBGGV6YCwaIUu3pf6M2F+eKykhRygoo4Wwo798U0GRPMeiMryEc7BXYdkA",
	"90jBjkQExzpJjreclvUPsYMbsFrJIMNQXIscGzuSJ0Wn0SjqvhUOr0Zg44HdhtPAboAX+9PI8s4Oc/L5",
	"Q6JzvOhjOsYt8EJxgw4wowWUhhfJsJ0iE8HMkXkej0EKJIl4285AnwkRozswVij5hPBF2MetsxENYfCu",
	"PFFKOuTfpJgkdBiDeV41mRAaFZOJwkIKFLwSfw8obpSqgMsn1AN/cSwK6XLQv4n1i8OB2klNBsdOIyTs",
	"w12lvqThG8iVKYQs7zRvbJpkm7zYkTRgnYlWyDERk80ewd4ZyCsu6nD0vTI1x+CEH99QlvAMyFB8k3Ar",
	"bvHONHJwVsERvvMeTtVrKGsXCYcjIk67dRSOA4xTJ7AJvVR8Em0gHSC+46JyNyZdeD6GXSzOG3ESuEfa",
	"gNHRm16JslDceT0eFeSR1L3d8Q42FqUnQQLsWIJkJPYWoZ6p58cCMvVkAbkqwCS5zw1TveJwapB4gmzf",
	"phVMCv+RXn8CibTGOOdGE59teWME7lfObbEKADdgLhvcdoOqt5V/fGS5RdSOR67Ug4DDciFpFh9RRiX3",
	"W20Mc7eXa/E77Gnb+oJ9r0JjsrkRGr0m9PL6itwrQ2oueSlkSSJRRmDn0oORzlSWES4LEkiRAhBydwgR",
	"kuAWyEcoAJGTd4BflHkgH0UBitz43WAuHCiBLo1pt/LjDbm8vur13IwuL76/WHr3aJBcC5rR1/4Ro5rj",
	"1gu34Fostr5yuL8l+PnVeZY7QFcFzegvgKG2+BwI3vabXy2X3tVKIki/kWtdidxvXXyywSmhKDxuiOlS",
	"x8s8lDesIHHK8EZo6pqbPc3oz01VkUCD+OnDScRL67wY2a3djh7dRSV2cJ6zG4Ffnvdg0E5wX4HZiRyI",
	"sIR73P08oNntui+GO0yCtUQbtYFHKBHm3LNS3MRx+MU90J/t58UIyFtGf1i+/g9hSIUHKDNxcSeKxwUm",
	"ZuzFAfipwLzXIC+vr1Ya8ucGZlxnJ3w/bIHE+4jVkBNuyW+r9+9mOfc3iPt4e4+5/yregdn3yFvfRedo",
	"hz77klYcdfJU+P0K4lvBsBj13rhmOyQ8CXVguzgOFws0oizDIKCVTSjwISwYTFlTMV5NO9RgB/GftVC4",
	"9Hmz/GkkHcJfuNAVF2mbdH1/osvwDl75vHCNTRtVuscjtSIZ1zUbXhEzIpXUrQY0IrdzFvkzLjnrkX9N",
	"9NqoGnALjSUHPENmiQUpPsPsGc4yt+uWfR2MK7fr1iUYGNfn/frGVDSjC+qex9NTk0mXaX7yKFTeuA+O",
	"gz3j1HNMR3dvsv+Gj3tG7NHlYZg5coyHRYrtuv0nAAD//+H1alpKFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
